on:
  repository_dispatch:
    types: [pdate-documentation]

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.4.2
